### ISSUE TITLE
semantic ui dropdown not working

### ISSUE THREAD

**Issue by meru-piparotar** [zelenin/yii2-semantic-ui#17]
as per your dropdown  example semantic ui  on http://yii2-semantic-ui.zelenin.pw/modules/dropdown.html not working.......

**Comment by zelenin** [comment]
http://yii2-semantic-ui.zelenin.pw/modules/dropdown.html it's working here.

**Comment by meru-piparotar** [comment]
use Zelenin\yii\SemanticUI\modules\Dropdown;
echo Dropdown::widget([
    'name' => 'select2',
    'selection' => 3,
    'search' => false,
    'fluid' => true,
    'disabled' => false,
    'defaultText' => 'Select an option',
    'items' => [
        '',
        'Categories' => [
            '1' => 'Clothing',
            '2' => 'Home Goods',
            '3' => 'Bedroom'
        ],
        null,
        'Order' => [
            '4' => 'Status',
            '5' => 'Cancellations'
        ]
    ]
]);


this code is not work only display dropdown bt not work ..Select::widget is working fine bt Dropdown::widget not work plz help replay asap.....

**Comment by meru-piparotar** [comment]
thanks......
