### ISSUE TITLE
GridView: in ActionColumn unavable action icon.

### ISSUE THREAD

**Issue by pol-den** [zelenin/yii2-semantic-ui#3]
```
use yii\grid\ActionColumn as BaseActionColumn;

class ActionColumn extends BaseActionColumn
 protected function initDefaultButtons()
    {
        if (!isset($this->buttons['view'])) {
...
                return Html::a('<i class="unhide icon"></i>', $url, $options);
            };
        }
        if (!isset($this->buttons['update'])) {
...
            return Html::a('<i class="edit icon"></i>', $url, $options);
            };
        }
        if (!isset($this->buttons['delete'])) {
...
       return Html::a('<i class="remove icon"></i>', $url, $options);
            };
        }
    }
```

**Comment by zelenin** [comment]
I don't understand you. What is your issue?

**Comment by pol-den** [comment]
колонка action в gridview для иконок использует
<span class="glyphicon glyphicon-trash"></span>, 
которые я предлагаю заменить на semantic <i class="remove icon"></i>

**Comment by pol-den** [comment]
ActionColumn использует для иконок glyphicon, которые я предлагаю заменить на вариант от semantic-ui.

**Comment by zelenin** [comment]
Конкретнее. Как проблема касается данного расширения?

**Comment by pol-den** [comment]
в GridView для редактирования, просмотра и удаления в ссылках иконки, использующие bootstrap.css, которые недоступны при его (bootstrap) отключении.

**Comment by zelenin** [comment]
да, верно.
Добавил в версии 0.2.4 ActionColumn и Pjax.
