### ISSUE TITLE
Валидация формы

### ISSUE THREAD

**Issue by fourteenmeister** [zelenin/yii2-semantic-ui#4]
После [этого коммита](https://github.com/zelenin/yii2-semantic-ui/commit/1be2fccf4475ffd18d2bf482c540b3b617aba481). Текст ошибки оказывается пустым (правило required).
![error](https://cloud.githubusercontent.com/assets/3837141/7579476/1355ea4a-f897-11e4-90a3-2e6da3bf7cc9.jpg)

**Comment by fourteenmeister** [comment]
Нашёл возможное решение:
В ActiveForm
```php
public function run()
    {
        parent::run();

        $this->getView()->registerJs('
jQuery("#' . $this->getId() . '").on("afterValidateAttribute", function(event, attribute, message) {
var $form = $(this),
    hasError = message.length > 0,
    $container = $form.find(attribute.container),
    $error = $container.find(attribute.error);

    if (hasError) {
        $error.attr("style", "display: table !important;");
    } else {
        $error.removeAttr("style");
    }
});
');
```

**Comment by zelenin** [comment]
fixed. https://github.com/zelenin/yii2-semantic-ui/commit/8d5e47bc77732d487c0b8a44e89bb561b3eee701
дело было в меняющихся после валидации классах поля ошибок: во время генерации поля там был класс hidden, а после появления ошибки исчезал, и js ActiveForm уже не мог найти поле.

**Comment by fourteenmeister** [comment]
Всё хорошо, за исключением одного - если сбросить форму стандартными способами ($('#form').reset();) - остаются те же самые иконки пустые.

**Comment by zelenin** [comment]
fixed
